import "../globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { dark } from "@clerk/themes"

const primary = Inter({
    subsets: ["latin"],
    variable: "--font-primary",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html
                lang="en"
                className="dark"
            >
                <body className={`${primary.variable} font-primary bg-black`}>
                    <main className="flex-1">{children}</main>
                </body>
            </html>
        </ClerkProvider>
    )
}
