import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { dark } from "@clerk/themes"
import Navbar from "@/components/layout/navbar"
import Footer from "@/components/layout/footer"
import LeftAside from "@/components/layout/left-aside"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html
                lang="en"
                className="dark"
            >
                <body className={inter.className}>
                    <Navbar />
                    <LeftAside />
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </ClerkProvider>
    )
}
